appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: c2tdxHDcVnugd47om5ZXMEpDSQPMO8rlVm/EbRCLZ0nteGCAE01q6V6/f7/kbjDV0gYTAufpU9Z/zD+Ky6Ic/jdHxFae0O5hvXyuPQVWxTyrC2rco8PJBjtuHf3UqEMOREewXEwauOKj2/iIoTk2UJSK+OOepGzHfQ4PGH4DshjqBpwdYvLYhQiu8wZFBNbtsSkoQ2+ezP9Rf8+HvFL9mlOy18hPSsX7h2Ja+9NTenOGUL8zLYiKxzkmT1QzTihWrr5FfsfS5ZJd3nVkxLgX0PJFo54+1ajK9casoRUk3b4nBX/lAU4VXJqZbMIWXmImOLYSrcpp/lCwj/uGYR6BaIAKBkA3PfeQY149Ohg8cIJ7vBWk09hTd7hnImg2CsYRxyjvhoi0Z1MoKDgnaD000hXsWJ5e9UCG70XYTIPid7CxYkSocR0ZQSprKBmA4MXGMyuULc9fa/d8mUnZiSEE5qPW0bjmmLUPSgreQ2XCAdtTKiTe/g3GBPsx+d8wHLe4ICmM1cBUXRK2ZOas2wDXTE7YzAVrmfDFNiB8Qm/Me5FPXUUpVI1zMJfOc/cyLYqX68vJNpH0jeZCEJ+isz9fxji9ZVnHs1uc/9tnCotfRnGmlfvsBgZGD2lJCvPWWFMQ010MLF77tArBj+zECyV9tq5u7+Y3MbI5RqoLPTYBXKg=}
bot:
  automerge: true
